### ISSUE TITLE
Tools for i18n

### ISSUE THREAD

**Issue by stalkerg** [kaisermann/svelte-i18n#1]
Currently, I use my implementation but very close to your library. 
The main problem with this approach - we still have no normal tools to:
- [x] 1. Get all keys from js/html files.
- [ ] 2. Check missing keys.
- [ ] 3. Check duplicate.
- [ ] 4. Probably integration with gettext format. 

Currently, I use, my small in-house scripts base on "i18n-extract" and it has many problems like:
1. i18n-extract can parse only JS it's why I parse dev bundle and lost key positions.
2. for use i18n-extract from nodejs and load translation from a project I converted this files to .mjs (nodejs can't in es6 import for js extension)

I think should be a better way, more integrated with svelte and probably with the rollup.

**Comment by kaisermann** [comment]
Yeah, exactly (calling the `_` method). I'm just thinking of making a little bit easier for the second case.

**Comment by stalkerg** [comment]
At first, we should use .mjs extension, without it, you can't get access from Node.JS

**Comment by kaisermann** [comment]
At least the first point of this issue is kind of covered by the CLI released on `v2`. I'll take a look on the rest of the items whenever possible! Any help is kindly welcome 😁(need to test it more throughly too...).
