### ISSUE TITLE
waitLocale throws an error when initLocale is null

### ISSUE THREAD

**Issue by jayk09** [kaisermann/svelte-i18n#100]
**Describe the bug**
This line:
https://github.com/kaisermann/svelte-i18n/blob/ceb694da741ac22fd2332497dc2327abdb011b8d/src/runtime/stores/locale.ts#L39
can cause this error because `getOptions().initialLocale` can be possibly `null`:
https://github.com/kaisermann/svelte-i18n/blob/ceb694da741ac22fd2332497dc2327abdb011b8d/src/runtime/index.ts#L12
https://github.com/kaisermann/svelte-i18n/blob/ceb694da741ac22fd2332497dc2327abdb011b8d/src/runtime/configs.ts#L43

**Logs**
`TypeError: Cannot read property 'split' of null`

**Expected behavior**
Should wait a locale with no errors.

**Information about your project:**

- `svelte-i18n` version 3.1.0

**Comment by ditorahard** [comment]
Is there any update? Been facing the same issue

**Comment by kaisermann** [comment]
Hey @jayk09 👋  Unfortunately I don't have the time to tackle this right now. However, are you calling `init` and defining at least a `fallbackLocale`? The `init` method should set the `initialLocale` value.

**Comment by jayk09** [comment]
@ditorahard in my case it was caused by incorrect regex so i18n wasn't initialized for service worker.. 
See https://github.com/kaisermann/sapper-template-i18n/pull/8/files
