### ISSUE TITLE
Cannot format a message without first setting the initial locale.

### ISSUE THREAD

**Issue by BirgitPohl** [kaisermann/svelte-i18n#102]
**Describe the bug**
I strictly followed the documentations of Svelte with Typescript and Svelte-i18n. 
Since I am new to Svelte I can not figure out, what the possible issue is. But I can't move forward. Ironically I call my current state a minimal repo. Here you are. :)

**Logs**
```bash
runtime.esm.js:15 Uncaught Error: [svelte-i18n] Cannot format a message without first setting the initial locale.
    at Array.V (runtime.esm.js:15)
    at create_else_block (App.svelte:29)
    at create_fragment (App.svelte:21)
    at init (index.mjs:1462)
    at new App (App.svelte:18)
    at main.ts:3
    at main.ts:8
```
```
(!) Plugin typescript: @rollup/plugin-typescript TS2732: Cannot find module './locale.en.json'. Consider using '--resolveJsonModule' to import module with '.json' extension

3 register('en', () => import('./locale.en.json'));
```
I followed the [documentations](https://github.com/kaisermann/svelte-i18n/blob/HEAD/docs/Getting%20Started.md#32-asynchronous) strictly.
I used the asynchronouse version of registering loaders.
However, when placing console.logs in the i18n.ts I noticed that those don't even appear.
Importing the i18n.ts into a main.ts would result into another error.

I have set the tsconfig as the error demanded and it is logical to output it, but when setting it, I still found the same error and I wonder, how come the tsconfig is not considered.

I have tried to set the initialLocal statically by using the string `en`.

**To Reproduce**
Clone https://github.com/BirgitPohl/Svelte-i18n-gnag
```
npm i
npm run watch:build
```

**Expected behavior**

- The documented setup delivers a working output
- i18n.ts gets to be magically called by svelte-i18n or a solution is delivered how i18n.ts should be imported or called by the project
- initalLocal is set
- A string from the json locales is shown

**Information about your project:**

```
MacOS 10.15.5
Chrome: Version 85.0.4183.121
Node: v14.13.1
Svelte: 3.0.0
Typescript: 3.9.3
Svelte-i18n: 3.1.0
```

**Comment by kaisermann** [comment]
Hey, @BirgitPohl  👋 It seems that you didn't import the `i18n.js` as you mentioned in your expected behavior:

`i18n.ts gets to be magically called by svelte-i18n or a solution is delivered how i18n.ts should be imported or called by the project`

If you continue to have issues after importing it, please create a new issue for it.

**Comment by BirgitPohl** [comment]
Sorry, to ask you again, because

1. I am a bit confused about a js file. I am having a Typescript project and I have placed the i18n.ts import now in every possible and reasonable file. I have the same error.

2. I wonder where the documentation writes how to import it.

> Expected behavior
> 
> [...]
> i18n.ts gets to be magically called by svelte-i18n or a solution is delivered how i18n.ts should be imported or called by the project
> [...]

I find it hard to guess it by myself.

**Comment by hugotox** [comment]
I have the same issue. The translation still works, but there's that error on client side
