### ISSUE TITLE
VSCode extension with inline localisation preview 

### ISSUE THREAD

**Issue by lukaszpolowczyk** [kaisermann/svelte-i18n#104]
**Is your feature request related to a problem? Please describe.**
Right in the `*.svelte` file I only see the id for message. I would like to see localisations directly in the `*.svelte` file.

**Describe the solution you'd like**
Create a VSCode extension that displays a localisation preview in a line, e.g. next to the code:
```html
<h1 class="title">{$_("app_title")}</h1>
```
...the extension adds the text "App Name" next to the reference to message:

```html
<h1 class="title">{$_("app_title") App Name }</h1>
```
**Important**: this is not supposed to be adding this text to the * .svelte file code, it has to be displayed using VSCode API, such as a color stamp in the [extension](https://marketplace.visualstudio.com/items?itemName=anseki.vscode-color):
![obraz](https://user-images.githubusercontent.com/16800535/98001722-e9173900-1ded-11eb-93e4-3d93c88e6e91.png)

Additionally:
* From within this inline text it should be possible to edit the content of this message.
* The extension should have a switch in the status bar to switch to a language other than the default language.
* When toggle the language and some message for the selected language does not exist, the default should be displayed but underlined as a warning, one with missing localisation.

**Describe alternatives you've considered**
I have to access individual localisation files.
I don't know if there are similar extensions that solve the same problem. 
EDIT: This react extension looks similar to my idea: https://marketplace.visualstudio.com/items?itemName=think2011.react-i18n

In the worst case, the localization may show up as a tooltip when you hover over `$_("app_title")`.

**How important is this feature to you?**
As for the app locating feature, it would be something big, very convenient.

**Additional context**
I understand that this issue may need to appear elsewhere, or it will be moved or made by anyone else.
Theoretically, a base extension could be created with this feature, and tailored to specific localization methods for different libraries and frameworks.

**Comment by thousandsofraccoons** [comment]
@lukaszpolowczyk  Have you tried [i18n-ally](https://marketplace.visualstudio.com/items?itemName=antfu.i18n-ally)?

**Comment by lukaszpolowczyk** [comment]
@thousandsofraccoons  Looks good. Write about extensions for code editors in the readme file.

**Comment by kaisermann** [comment]
Nice suggestion, @thousandsofraccoons! I've added it to the docs: https://github.com/kaisermann/svelte-i18n/blob/master/docs/Getting%20Started.md#11-vscode-extension
