### ISSUE TITLE
Replacing content of svelte file with undefined

### ISSUE THREAD

**Issue by ibubenko** [kaisermann/svelte-i18n#108]
When running the following command:
`svelte-i18n extract ./src/routes/*.svelte ./src/i18n/en.json -s`

getting this error:
```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/igor/workspace/gl/fifa/web/node_modules/svelte-i18n/dist/cli.js:17:3743
    at async /Users/igor/workspace/gl/fifa/web/node_modules/svelte-i18n/dist/cli.js:17:3718
```
Content in file Login.svelte is replaced by `undefined`. Initial content of the file was:
```
  import { _ } from 'svelte-i18n'
  import { okta } from '../services';

  import Login from '@components/Login.svelte';

  function handleLogin() {
    console.log(username, password);
    okta.login({ username, password })
      .then(r => {
        console.log(r);
        if (r.status === 'MFA_REQUIRED') {
          step = 'mfa';
          transaction = r;
        } else if (r.status === 'SUCCESS'){
          console.log(r);
          return okta.getUrl({ sessionToken: r.sessionToken });
        }
        console.log(JSON.stringify(r, null, 2));
      })
  }

  function handleVerify() {
    okta.verify({
        id: transaction._embedded.factors[0].id,
        stateToken: transaction.stateToken,
        passCode
      })
      .then(r => {
        console.log(r);
        return okta.getUrl({ sessionToken: r.sessionToken });
      })
      .then(url => {
        console.log('url: ', url);
      })
      .catch(e => {
        console.error('verify error: ', e);
      })
  }

  function handleSend() {

  }

  let factors;
</script>

<svelte:head>
  <title>{$_('login.title')}</title>
</svelte:head>

<Login 
  onLogin={handleLogin}
  onVerify={handleVerify}
  onSend={handleSend}
  factors={factors}
/>

```

**Comment by kaisermann** [comment]
I'm not sure what's happening here. Seems to be working If I copy your component, prepend the missing `<script>` tag and try to extract the messages.

![image](https://user-images.githubusercontent.com/12702016/99802129-e61e8700-2b15-11eb-932e-f5b53024d455.png)

**Comment by ibubenko** [comment]
Hi, I was able to reproduce that and not sure if it's my or sade fault:

this destroy my file: svelte-i18n extract ./src/**/*.svelte ./src/i18n/en.json -s
this one works great: svelte-i18n extract "./src/**/*.svelte" ./src/i18n/en.json -s (notice "" )

So I believe that sade somehow gets my second file in row and makes that as output file.

So I'm good, thanks for great i18n tool.

**Comment by kaisermann** [comment]
Hmmm 🤔  this is probably happening because your shell is expanding the glob pattern, it's not a `sade` issue. I've added a section to the CLI docs mentioning this behavior.
