### ISSUE TITLE
$local returns the wrong local.

### ISSUE THREAD

**Issue by RemiKalbe** [kaisermann/svelte-i18n#111]
From the following i18n config
```js
import { addMessages, init, getLocaleFromNavigator } from "svelte-i18n";

import enUs from "../locales/enUs.json";
addMessages("en-US", enUs);

init({
  fallbackLocale: "en-US",
  initialLocale: getLocaleFromNavigator()
});
```
Doing the following
```svelte
<script>
import { locale } from "svelte-i18n";
$: console.log($locale)
</script>
```
returns `fr-FR`. <br>
Isn't `$locale` supposed to return the locale currently used by svelte-i18n? As `fr-FR` is not in the dictionary shouldn't it fallback to `en-US `?

**Information about your project:**

- Tried on chrome and safari

- MacOS 11

- v3.3.0

- Rollup

**Comment by kaisermann** [comment]
Hey, @RemiKalbe 👋  Currently, the `$locale` store points to locale that was set via `init` or `locale.set`/`$locale = ...`. The library uses the fallback locale on a per-message basis. In other words, it tries to load a specific message with the current locale, if none is found, it looks in the fallback locale dictionary.

**Comment by RemiKalbe** [comment]
Ohh ok! Thank you for the clarification.
I'm building a datepicker, and based on the `$locale` doing some stuff (without using i18n methods, I just want to know what the current locale is). The thing is, I don't want `$locale` to return `fr-FR` if there isn't any message registered to that locale. For now I'll just check if the dictionary is null based on the locale.
Do what you want with this use case, the "workaround" isn't at all complicated. 

It's just that I find it odd to return a locale that isn't registered, because you know that there will never be any message from the `fr-FR`, locale so it will always fallback.

**Comment by kaisermann** [comment]
> because you know that there will never be any message from the fr-FR, locale so it will always fallback.

Not necessarily, but we could check the locale queue to see if there's any partial dictionary to be loaded. If not and the locale isn't registered in the dictionary, we could possibly set it to the fallback one. 🤔

**Comment by RemiKalbe** [comment]
I also forgot to add that for exemple, if I use $date, it will be formatted in French even tho all the page is in English.

**Comment by kaisermann** [comment]
What would happen if someone wants to use the time, date, and number methods for a certain locale that doesn't have any messages registered? I'm not 100% sure if this is a valid scenario though. Also, the change I mentioned above would be a breaking one.

**Comment by RemiKalbe** [comment]
> edit: answering myself, in that case, the dev could explicitly pass the desired locale for these formatted methods

Was gonna say the same.

From https://www.i18next.com/overview/api#language it seems like it acts like your library. I find it strange, I don't really see a reason for it 🧐.
Maybe then adding an option to the init method to force the $locale to change if there isn't any message for this locale ?

**Comment by kaisermann** [comment]
Rethinking this 🤔  `fr-FR` should be the actual locale if the store was indeed set to it. `fr-FR` not being in the dictionary shouldn't mean that the app should resort completely to the fallback local. It's just that, for some reason, there weren't any messages to load.
