### ISSUE TITLE
Translation of strings outside of svelte file scope

### ISSUE THREAD

**Issue by mhatvan** [kaisermann/svelte-i18n#114]
I was wondering if it is possible to use svelte-i18n formatting outside of svelte files?
Basically I have datatable configuration settings in a separate Typescript file that I want to reuse for multiple tables.
 
```
export const settings = {
  labels: {
    search: $t('component.dataTable.searchAll'), // Doesn't work outside of .svelte files
    previous: 'Previous', // Should also get translated ideally
    next: 'Next', // Should also get translated ideally
  },
  sortable: true,
  pagination: true,
  columnFilter: false,
  scrollY: false,
};
```

I tried `getMessageFormatter()` but its probably not meant for that.

**Comment by mhatvan** [comment]
Oh, I was actually getting it to work by changing settings to accept a function parameter and passing `$t` from the component to the file.
Issue can be closed imo.

**Comment by kaisermann** [comment]
Hey @mhatvan 👋 you could also subscribe to the `t` store and re-translate your object whenever it changes!

**Comment by koxta** [comment]
Much better way is to use `get` from svelte store to

```
import { get } from "svelte/store";
import { _ } from "svelte-i18n";
const f = get(_);

f('your-message');
```
