### ISSUE TITLE
Frontend doesn't update translated strings after $locale change

### ISSUE THREAD

**Issue by mhatvan** [kaisermann/svelte-i18n#115]
I can't seem to get the Svelte frontend (no Sapper) to update the translated strings to another language after `$locale` changes.

My code looks like this:
```
        <select
          bind:value="{$locale}"
          on:change="{handleChange}"
          class="input-field"
          id="locale"
          name="locale"
        >
          {#each $locales as locale}
            <option value="{locale}">
              {$t(`component.languageDropdown.${locale}`)}
            </option>
          {/each}
        </select>
```

I can see that html lang changes when I switch locale and I get the correct updated values, but the frontend always displays the en version even when I switch to other locales...

**Comment by mhatvan** [comment]
Interesting: only my `en.json` had content, `de.json` and `fr.json` had all the translation keys set to empty string because I didn't fill them in yet intentionally. As soon as I filled out the content, the correct translations were displayed. In my opinion, when strings are missing, the frontend should display it as e.g. `page.title` instead of falling back to the language that was set before.

**Comment by kaisermann** [comment]
Hey @mhatvan 👋  It doesn't fallback to the previous language, it fallbacks to the fallback language. In your scenario, `en` seems to be the fallback locale and as the lib didn't find the messages on the other dicts, it decided to show the fallback values. What is your vision for the role of a fallback locale? When would it be used?

**Comment by mhatvan** [comment]
After thinking about it again, I guess it's the right behavior. 

It was just confusing since the ui doesn't update when switching languages, as it sticks with the fallback language. 

Therefore I thought that svelte-i18n was configured wrong on my side.
