### ISSUE TITLE
npm install broken?

### ISSUE THREAD

**Issue by gggiiia** [kaisermann/svelte-i18n#119]
**Describe the bug**
npm i svelte-i18n gives an error, could be npm side error and only temporary

**Logs**
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for svelte-i18n@3.3.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**To Reproduce**
run 
`npm i svelte-i18n
`

**Comment by kaisermann** [comment]
Hey @gggiiia 👋 

Seems it was a temporary npm issue:

![image](https://user-images.githubusercontent.com/12702016/106398135-df52a100-63ef-11eb-867d-a82ff99af347.png)
