### ISSUE TITLE
TypeError: e.lastIndexOf is not a function

### ISSUE THREAD

**Issue by chovy** [kaisermann/svelte-i18n#122]
trying to use with sapper. I get this error.

`TypeError: e.lastIndexOf is not a function`

in client.js and server.js I added: `import './i18n/locale';
`

```
import { init, addMessages } from 'svelte-i18n';
import { de, fr, en } from './i18n';

init({
  fallbackLocale: 'en',
  initialLocale: {
    navigator: true,
  },
});

addMessages('de', de);
addMessages('fr', fr);
addMessages('en', en);

```

**Comment by kaisermann** [comment]
Hey @chovy 👋 That seems to be the API from v2. If you're using v3 and want to get the navigator locale check [this](https://github.com/kaisermann/svelte-i18n/blob/main/docs/Methods.md#getlocalefromnavigator)
