### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by cupcakearmy** [kaisermann/svelte-i18n#123]
Hey there,

I have a few questions 😀 
I've read all the /docs but could not wind my answers there.

1. Any way to handle plurals? Something like `{ cars: 'cars | one car | {count} cars'}` and `$_('cars', { count: 1})`
2. Is there a way to assign defaults to templates? e.g. `{ delete: 'Delete {what}'}` would default to `Delete foo` if no value is given

Thanks for the project!
Btw now that Github discussions are released maybe you could enable them, so you don't end up with QA tickets like this one. 😆 🙈 
Sryy

**Comment by DmitryMyadzelets** [comment]
The questions are related to the `Svelte`, not the package.
1. An [example with cars](https://svelte.dev/repl/14cd7b90c7c74c2d999f87e7793f98f2?version=3.31.2)
2. See the tutorial: https://svelte.dev/tutorial/default-values

**Comment by cupcakearmy** [comment]
@DmitryMyadzelets  Thanks for taking the time for doing a REPL, however this has nothing to with Svelte itself.

1. Many i18n library have support for plurals because it makes sense instead of defining it our selfes. Examples for [vue](https://kazupon.github.io/vue-i18n/guide/pluralization.html#accessing-the-number-via-the-pre-defined-argument) & [react](https://www.i18next.com/translation-function/plurals). Of course one could define multiple translation keys and use the ternary operator, but thats ugly and unnecesary verbose.
2. You are talking about default values for component props. I'm referring to default values for translations string variables.

**Comment by DmitryMyadzelets** [comment]
Then, going deeper I'd add that such plugin shouldn't really exist for `Svelte`. There is plenty of sophisticated framework-agnostic libraries. Some create wrappers for frameworks like `Vue` but I'm not convinced they really had to. 

This plugin is a *simple thing*. I've found a decent intro to it (take a look at the pluralization part): https://lokalise.com/blog/svelte-i18n/, but it doesn't really differ from the straightforward approach I've shown you.
Not sure if there is an answer to your second question there.

**Comment by cupcakearmy** [comment]
Thanks for linking the docs, did not know svelte i18n was using format js
https://formatjs.io/docs/core-concepts/icu-syntax/#plural-format this was what I was searching for, thanks.
The default value remains a bit of a pain but i guess that will stay like this

**Comment by kaisermann** [comment]
Hey, @cupcakearmy 👋 Default value for an interpolated value should be handled by the app's side, as the ICU syntax does not support this feature. 

@DmitryMyadzelets Thanks for the other answers!
