### ISSUE TITLE
Getting translation value in the script

### ISSUE THREAD

**Issue by eXodes** [kaisermann/svelte-i18n#124]
First of all, thank you so much for making this plugin. 

I'm quite new to Svelte and I have a few question regarding accessing the store value for the content.  As per examples. this is how you get the value from the i18n store.

```jsonc
/* data.json */
{
  "property": "Hello",
}
```

```js
/* i18n.js */
register('en', () => import('data/en.json'));

init({
  fallbackLocale: 'en',
  initialLocale: getLocaleFromNavigator(),
});

locale.set('en');
```

```svelte
/* App.svelte */
<script>
  import { _ } from 'svelte-i18n';
</script>

<h1>{$_('property')}!</h1>
```

But if I need to access the store value in the script section, how do I do it? I cannot use the unsub method for the store as `_` is not exactly a single writable store. 

I tried getting the value as per my solution below but it doesn't work in the script section. 
```svelte
/* App.svelte */
<script>
  import { _ } from 'svelte-i18n';

  console.log($_('property')); // returned 'property'
  console.log(_('property')); // Error: te is not a function'
  console.log(get(_)('property')); // Error: [svelte-i18n] Cannot format a message without first setting the initial locale.
</script>

<h1>{$_('property')}!</h1>
```

Is there something that I missed? Does the store content value can only be accessible in the markup?

_Why do I need this?_ Maybe for edge cases where I need to use the content value in a function as I'm still exploring the plugin.

**Comment by Fanda36** [comment]
Hi,

you can get `dictionary` it is Svelte writable object https://svelte.dev/docs#writable

It is possible to read current value of writable object by `get` https://svelte.dev/docs#get

```js
import {dictionary} from 'svelte-i18n';
import {get} from 'svelte/store';

console.log(get(dictionary));
```

**Comment by eXodes** [comment]
Thank you @Fanda36.
