### ISSUE TITLE
TypeScript template argument for `json` breaks the markup

### ISSUE THREAD

**Issue by illright** [kaisermann/svelte-i18n#125]
**Describe the bug**
When you use `svelte-i18n` with TypeScript and attempt to specify the return type of `$json`, the compiler reports an unexpected token.

**Logs**
An error from running `svelte-check` on the project root:
```
/home/illright/i18n-ts/src/App.svelte:7:25
Error: Unexpected token (svelte)
<main>
    {#each $json<number[]>('test') as num} {num} {/each}
	<h1>Hello {name}!</h1>
```

**To Reproduce**
* clone a fresh Svelte template: `npx degit sveltejs/template i18n-ts`
* set up TypeScript: `cd i18n-ts; node scripts/setupTypeScript.js; pnpm install`
* add `svelte-i18n`: `pnpm add svelte-i18n`
* add a `src/i18n.ts` with the following content:
```ts
import { addMessages, init } from 'svelte-i18n';

addMessages('en', { test: [ 5 ] });

init({
  fallbackLocale: 'en',
  initialLocale: 'en',
});
```
* import it in `main.ts`:
```ts
import App from './App.svelte';
import 'i18n';
```
* use a templated `$json` in `App.svelte`:
```svelte
<script lang="ts">
  import { json } from 'svelte-i18n';
  export let name: string;
</script>

<main>
  {#each $json<number[]>('test') as num} {num} {/each}
  <h1>Hello {name}!</h1>
  <p>Visit the <a href="https://svelte.dev/tutorial">Svelte tutorial</a> to learn how to build Svelte apps.</p>
</main>
```
**Expected behavior**
This code should compile and recognize the type of `num`.

**Information about your project:**

- Your browser and the version: Chrome, latest

- Your operating system: Manjaro Linux

- `svelte-i18n` version: 3.3.0

- Whether your project uses Webpack or Rollup: Rollup

**P.S.** Your bug report template says `svelte-preprocess`, might wanna update it :p

**Comment by kaisermann** [comment]
@illright Hey 👋 I don't exactly remember why I expected this syntax to work out of the blue. Unfortunately, I don't think Svelte supports the syntax for passing generics. This should be handled by `svelte-preprocess`, but it's not trivial.
