### ISSUE TITLE
Can not find types in 3.3.5

### ISSUE THREAD

**Issue by JuseongJee** [kaisermann/svelte-i18n#131]
(Please understand my pure english)

In 3.3.5 types cannot be found by the path written in package.json 
"types": "types/runtime/index.d.ts",

The path of index.d.ts file which is released in 3.3.5 is types/runtime/runtime/index.d.ts

**Comment by kaisermann** [comment]
Hey, @JuseongJee 👋 Thanks for the report! Hopefully fixed in 3.3.6 😁
