### ISSUE TITLE
lang attribute on documentElement is anyways set to "null"

### ISSUE THREAD

**Issue by tombstonedguy** [kaisermann/svelte-i18n#133]
**Describe the bug**
i try to use the package in a server-generated html-page which renders out the correct lang-attribute on the html-tag.
when loading and interpreting the script contents the lang attribute is changed to "null" caused by the initial value in the underlying store.

```
const $locale = writable(null);

$locale.subscribe((newLocale: string) => {
  current = newLocale;

  if (typeof window !== 'undefined') {
    document.documentElement.setAttribute('lang', newLocale);
  }
});
```
currently i am not able to get the desired value in time to init the package with this value.

**Expected behavior**
It would be cleaner for integration-scenarios to not nullify the html-page value if there is already one set. this should be done when the store was properly initialized.

maybe the following snippet could be a proper solution:

```
if (typeof window !== 'undefined' && newLocale !== null) {
  document.documentElement.setAttribute('lang', newLocale);
}
```

**Comment by kaisermann** [comment]
Release in 3.3.9 🎉
