### ISSUE TITLE
Timezone change not recognized

### ISSUE THREAD

**Issue by d-s-e** [kaisermann/svelte-i18n#148]
I'm using the $time store to get a localized version of timestamps and also to display the current time in the application.

At first, everything seems to be correct:

    > new Date()
    Fri Jul 02 2021 12:19:54 GMT+0200 (Central European Summer Time)
    > $time(new Date(), {format: 'medium'})
    "12:19:54"

But when I change the timezone on the system the browser is running, the output is wrong:

    > new Date()
    Fri Jul 02 2021 19:22:52 GMT+0900 (Japan Standard Time)
    > $time(new Date(), {format: 'medium'})
    "12:22:52"

Only after reloading the application in the browser the output is correct again. I would expect the output to adapt to the correct time without having to reload.

I'm working on Linux systems with several browsers.

**Comment by d-s-e** [comment]
After some investigation I found out, that this can be solved by adding the current timezone to the options:

        $time(new Date(), {format: 'medium', timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone})

But that does not explain, why the timezone is considered after initializing the application, but not after a timezone change while the app is running.

**Comment by kaisermann** [comment]
Hey @d-s-e, when you switched the system's timezone, did you also change the `$locale` dictionary to reflect that? The `$time` store is tied to the locale set on `$locale`
