### ISSUE TITLE
How to insert html tags into message?

### ISSUE THREAD

**Issue by robsch** [kaisermann/svelte-i18n#149]
Sorry for that simple question, but I'm not able to find it out by myself.

How can I define html tags in a localized string? E.g., with `"welcome-message": "Welcome <strong>{name}</strong>!"` the contained tags are not converted to real tags when I try to output the message with `$_('welcome-message', {values: {name: "Bob"}})`. What I see in my browser is `Welcome <strong>Bob</strong>!`

What do I have to do to accomplish that?
 
Using svelte-i18n in version 3.3.9.

**Comment by andreyluiz** [comment]
You can use the `@html` modifier.

```javascript
<div class="center wide">
  {@html $_("hello.world", {
    default:
      "Hello<br />World!",
  })}
</div>
```

**Comment by robsch** [comment]
Oh... Thank you @andreyluiz . I thought it. Cannot be that hard. But I didn't see the forest for the trees, as it seems.
That's it. Thanks again!
