### ISSUE TITLE
Embedded Tag Support as per Intl MessageFormat example

### ISSUE THREAD

**Issue by dkozma** [kaisermann/svelte-i18n#150]
**Is your feature request related to a problem? Please describe.**
I'm looking to add a dynamic tag like they do in the [`intl-messageformat` docs](https://formatjs.io/docs/intl-messageformat/#rich-text-support):

```js
new IntlMessageFormat('hello <b>world</b>', 'en').format({
  b: chunks => <strong>{chunks}</strong>,
})
```

I'm not sure how to do something like this in Svelte, or if it can be done, if this library supports it.

**Describe the solution you'd like**
It would be great to have something as close to the `intl-messageformat` example as possible.

**Describe alternatives you've considered**
I've just been using very simple HTML tags for now (or not embedding tags at all).

**How important is this feature to you?**
I would say on a scale from 3-5 it's a 4 (unless I can find a workaround).

**Additional context**
None.

**Comment by kaisermann** [comment]
Hey, @dkozma 👋  The current workaround is to use the `{@html $_(...)}` modifier. It's not ideal, though. I'm not sure there's a way to support markup chunks given the nature of svelte's markup language.

**Comment by dkozma** [comment]
Thanks @kaisermann - I figured that was the case but didn't know if someone who knew Svelte better than I did had a solution for that 😄 . I'll try the workaround you mentioned for now and close this issue in the meantime. Appreciate the response.
