### ISSUE TITLE
Sapper/SvelteKit i18n separation by route

### ISSUE THREAD

**Issue by thousandsofraccoons** [kaisermann/svelte-i18n#152]
**Is your feature request related to a problem? Please describe.**
Thank you once more for a great library. So the question is how to handle big-size projects with many pages. Is there any way to split translations by route and load only needed?

**Describe the solution you'd like**
Let's say
- en
- - main
- - about
- - etc 
- de
- - main
- - about
- - etc

With the ability to asynchronously load any JSON in ssr/runtime from index.svelte of the selected route.
```
import { _, get, locale} from "svelte-i18n";
$: if (lang) get(async () => import(`../${locale}/main.json`))
```

**How important is this feature to you?**
Probably it would be useful on every big-size project.

**Comment by Basssiiie** [comment]
I ran into the same problem. While not perfect, I solved it like this.
```svelte
<script context="module">
	import { register, waitLocale } from "svelte-i18n";

	register("en", () => import("./localisation/extra/en.json"));
	register("nl", () => import("./localisation/extra/nl.json"));
</script>

<script>
	import { locale } from "svelte-i18n";
</script>


{#await waitLocale($locale)}
	<p>Loading ...</p>
{:then _}
	<slot/>
{/await}
```
Basically I have a svelte file which loads the additional localisation in the context of a `module`, before it renders the actual content in `<slot/>`. I'm not sure if it's the best but it might be a good start for you as well. It probably ruins SEO though, but in that case you might be able to replace the async calls with sync `addMessages` calls.

Since I'm quite new to Svelte/SvelteKit, if you'd have any tips I'd love to hear them.

**Comment by thousandsofraccoons** [comment]
@Basssiiie interesting one. Have you tried to register() in `preload`?

**Comment by Basssiiie** [comment]
@thousandsofraccoons I couldn't get it to work in combination withe Svelte Kit's static adapter. Furthermore `preload` is renamed renamed `load` in Svelte Kit IIRC and `register()` is by itself not async.

**Comment by Basssiiie** [comment]
Update, after some fiddling I have managed to get `load` to work with the static adapter and it seems to hydrate as well

```

**Comment by thousandsofraccoons** [comment]
@Basssiiie @kaisermann for me it doesn't work, unfortunately. `/src/server.js` translations overriding new registered translations for route :(

**Comment by thousandsofraccoons** [comment]
@Basssiiie  @kaisermann  After experimenting turns out that separation by route works. Only one thing for Sapper tho - when I return something from `preload` - translation getting broken. With declaring `wirtable` in `module` it works well. Thank you. Can close this issue.
