### ISSUE TITLE
A convenient way to translate strings in JavaScript code

### ISSUE THREAD

**Issue by Tal500** [kaisermann/svelte-i18n#170]
Svelte-i18n formatting gives a store that reproduce a function that translate a given word, meaning:
_: () => store
and the store has value of a function: (message) => translation

This is fine, and on Svelte files the syntax `$_(messsage)` works great, first the syntax `($_)` tells Svelte to subscribe to the store value, and the invocation with the parameter (message) gets the translated string.

However, if you can't use the convenient syntax `$_(message)` in a javascript/typescript file you use with your svelte project, since `$_` isn't defined symbol of JS.
In order to be able to use this syntax, I had to write the following utility code, which I suggest this project to adapt to make life easier for people:

```js
import { derived } from 'svelte/store';
import { format } from 'svelte-i18n';

function $_(messsage: string) {
    return derived(format, ($format) => $format(messsage));
}
```

This function returns (as I believe it should) a store that represents the translated value of the message.

This allow up for example to call in JavaScript/TypeScript code some `custom_alert($_('important-warning-message'))`, while `custom_alert` is a function takes a store for a string and display it to the user as an alert.
This alert should update the translation of the message if the locale has been changed.

Do you agree? Do you believe we should have another convention?

**Comment by vincenzoraco** [comment]
This issue has been addressed here https://github.com/kaisermann/svelte-i18n/issues/124

However, I can agree that it is not the nicest thing to write. I got it working creating the following function:

```js
import { get } from 'svelte/store'
import { dictionary } from 'svelte-i18n'

const translate = key => {
    if (!user_language || !get( dictionary )[ user_language ]) {
	return key
    }
		
    return get( dictionary )[ user_language ][ key ]
}
```

**Comment by Tal500** [comment]
> This issue has been addressed here #124
> 
> However, I can agree that it is not the nicest thing to write. I got it working creating the following function:
> 
> ```js
> import { get } from 'svelte/store'
> import { dictionary } from 'svelte-i18n'
> 
> const translate = key => {
>     if (!user_language || !get( dictionary )[ user_language ]) {
> 	return key
>     }
> 		
>     return get( dictionary )[ user_language ][ key ]
> }
> ```

Thank you for this solution. I have showed a relatively clean alternative, by defining in the library the symbol `$_` above in addition to `_`, what is your opinion?

**Comment by BartokIT** [comment]
> This issue has been addressed here #124
> 
> However, I can agree that it is not the nicest thing to write. I got it working creating the following function:
> 
> ```js
> import { get } from 'svelte/store'
> import { dictionary } from 'svelte-i18n'
> 
> const translate = key => {
>     if (!user_language || !get( dictionary )[ user_language ]) {
> 	return key
>     }
> 		
>     return get( dictionary )[ user_language ][ key ]
> }
> ```

Sorry but where is defined the `user_language`  variable? 
I've not found that there is the `locale` store but it cannot be substituted because is a store.

**Comment by kaisermann** [comment]
@BartokIT You can use the same `get(store)` strategy

**Comment by vincenzoraco** [comment]
> > This issue has been addressed here #124
> > However, I can agree that it is not the nicest thing to write. I got it working creating the following function:
> > ```js
> > import { get } from 'svelte/store'
> > import { dictionary } from 'svelte-i18n'
> > 
> > const translate = key => {
> >     if (!user_language || !get( dictionary )[ user_language ]) {
> > 	return key
> >     }
> > 		
> >     return get( dictionary )[ user_language ][ key ]
> > }
> > ```
> 
> Sorry but where is defined the `user_language` variable? I've found that there is the `locale` store but it cannot be substituted because is a store.

`user_language` is a variable that you need to provide to the function - it could come from user object, a store, a cookie, from the local storage, etc.

**Comment by vincenzoraco** [comment]
> > This issue has been addressed here #124
> > However, I can agree that it is not the nicest thing to write. I got it working creating the following function:
> > ```js
> > import { get } from 'svelte/store'
> > import { dictionary } from 'svelte-i18n'
> > 
> > const translate = key => {
> >     if (!user_language || !get( dictionary )[ user_language ]) {
> > 	return key
> >     }
> > 		
> >     return get( dictionary )[ user_language ][ key ]
> > }
> > ```
> 
> Thank you for this solution. I have showed a relatively clean alternative, by defining in the library the symbol `$_` above in addition to `_`, what is your opinion?

Yes, I agree - a clean approach, however, it is identical to the function that we use outside of the script tag and it might cause confusion.

I prefer to have explicit functions name when using them in the script tag, especially in these cases where I believe we don't use it so often - where `$_` would be used much more on the view section.

At the end, it's the maintainer choice we can only suggest :)

**Comment by sebastianrothe** [comment]
The proposed solutions above are not enough. If I need to dynamically access a message string with dot-notation, then it wont work:

```javascript
// fails, if key = "string1.string2"
get( dictionary )[ user_language ][ key ]
```

**Comment by kaisermann** [comment]
@sebastianrothe You can manually subscribe to the `format`/`_`/`t` store and use it as any other js function.

```js
import { _ } from "svelte-i18n";

let formatMessage;

_.subscribe((storeFormat) => (formatMessage = storeFormat));

formatMessage("string1.string2");
```

**Comment by sebastianrothe** [comment]
> 

Thank! Good to know. I solved it with my a store and loading the message in the component.
