### ISSUE TITLE
Fallback Locale

### ISSUE THREAD

**Issue by subpx** [kaisermann/svelte-i18n#19]
My main use case for i18n, is supporting multiple versions of English. For example US and AU. 
Many words have different spelling, but they are both English so mainly the same.

Instead of having duplicate dictionaries with some minor differences, It would be useful to have a fallback dictionary, so that only the differences would need to be in the 'other' english dictionaries.

Thoughts on this?

**Comment by chovy** [comment]
I think that's why you can merge in objects to the dictionary. So en_AU can merge in en_US and you can override with the differences.

**Comment by subpx** [comment]
Just looks like that is for adding another dictionary.

**Comment by chovy** [comment]
you can merge two objects before you set the au one.


`au: Object.merge(us, { Hello: 'Howdy mate!' })`

**Comment by subpx** [comment]
You could always use JS to write less code and merge dictionary objects. It would still result in duplicate code and a little bit of unnecessary handling of the dictionary objects.

**Comment by subpx** [comment]
Hhahahahha we would never say Toss or shrimp!

**Comment by chovy** [comment]
Not according to Crocodile Dundee.

**Comment by kaisermann** [comment]
I completely agree that also looking for the message in the more generic locale should be the default behaviour. Duly noted for `v2.0.0` 😁

**Comment by subpx** [comment]
@kaisermann awesome!

**Comment by kaisermann** [comment]
Fixed on `v2.0.0` 🎉

**Comment by kaisermann** [comment]
- [ ]
