### ISSUE TITLE
Add possible to describe function for plural

### ISSUE THREAD

**Issue by stalkerg** [kaisermann/svelte-i18n#2]
In some languages, we have more complicated rules for plural. 
Like in Russian https://gist.github.com/tomfun/830fa6d8030d16007bbab50a5b21ef97 

Really good list of rules: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals

**Comment by kaisermann** [comment]
Sorry for taking so much time to answer this issue. It was address in #6 along with the support for `svelte v3`
