### ISSUE TITLE
Looks like short lang codes don't work (ie: en, de, fr)

### ISSUE THREAD

**Issue by chovy** [kaisermann/svelte-i18n#20]
`Uncaught Error: [svelte-i18n] Locale "en-US" not found.
    at Object.g.set (i18n.mjs:1)
    at locale.js:4
    at main.js:12`

**Comment by chovy** [comment]
Tried changing to long codes, still get this error. Its not finding the dictionary I guess (copied from readme and imported into main.js)

**Comment by chovy** [comment]
dictionary has to come above everyting else.

**Comment by chovy** [comment]
Well I got en to load but the only way I can get german to load is to use ?lang=de

if i change chrome to use German. It is ignored even though window.navigator.language is set to 'de'. I still get english

**Comment by chovy** [comment]
ok so it looks like `navigator`, `hash` and `search` are mutually exclusive. It only uses the last one your provide.

**Comment by kaisermann** [comment]
@chovy That behaviour will be fixed on `v2.0.0`.  The precedence will be: `navigator` > `search` > `hash.
