### ISSUE TITLE
Use translation inside script area

### ISSUE THREAD

**Issue by Spaceman2019** [kaisermann/svelte-i18n#201]
Hi, 
I want to store a translation in a variable to pass it to a component. How can I do this? I haven't found an example of this.
Thanks

**Comment by kaisermann** [comment]
Hey, @Spaceman2019 👋 There are a few ways to do this. One is to subscribe to the `_`/`t`/`format` store:

```js
import { format } from 'svelte-i18n`

let localFormat

format.subscribe(value => (localFormat = value))

localFormat('home.page.title')
```

If it's not a code hot path, you can use the `get` function from 'svelte/store' to use the `_` function outside of a svelte context:

```js
import { get } from 'svelte/store'
import { _ } from 'svelte-i18n`

console.log(get(_)('home.page.title'))
```

**Comment by antoine-duc** [comment]
Hello,

I was trying to do the same.
I'm using typescript.
I can't type the "localFormat" as MessageFormatter since it's not exported from the library.
Exporting types would be great if possible.

Thanks

**Comment by kaisermann** [comment]
I had a different idea and exposed a method called `unwrapFunctionStore` to help with my first suggestion:


```js
// some-file.js
import { unwrapFunctionStore, format, formatNumber } from 'svelte-i18n';

const $formatNumber = unwrapFunctionStore(formatNumber);
const $format = unwrapFunctionStore(format);

console.log(
  $formatNumber(1000, 'en-US', { style: 'currency', currency: 'USD' }),
); // $1,000.00
console.log($format('Hello {name}', { name: 'John' }, 'en-US')); // Hello John
```

**Comment by antoine-duc** [comment]
Thank you, it's very convenient.
