### ISSUE TITLE
svelte-i18n cli extract - Typescript support?

### ISSUE THREAD

**Issue by petrsiegl** [kaisermann/svelte-i18n#205]
**Describe the bug**
Extracting translations with `svelte-i18n extract src/lib/components/Footer.svelte` fails when declaring variable with Typescript's type.
Tried with `--configDir /home/user/work/booking/web` as well.

**Logs**
See stacktraces.

**To Reproduce**
This will fail:
```
<script lang="ts">
     import { _ } from 'svelte-i18n';

     export let name: string;
</script>
{$_('test')}
```

This works:
```
<script lang="ts">
     import { _ } from 'svelte-i18n';
</script>
{$_('test')}
```

**Expected behavior**
Expect it to work the same in both cases mentioned.

**Stacktraces**

<details>
  <summary>Stack trace</summary>

$ /home/user/work/booking/web/node_modules/.bin/svelte-i18n extract  src/lib/components/Footer.svelte
/home/user/work/booking/web/node_modules/svelte/compiler.js:16675
            const error = new CompileError(message);
                          ^

CompileError [ParseError]: Unexpected token
    at error (/home/user/work/booking/web/node_modules/svelte/compiler.js:16675:20)
    at Parser$1.error (/home/user/work/booking/web/node_modules/svelte/compiler.js:16753:10)
    at Parser$1.acorn_error (/home/user/work/booking/web/node_modules/svelte/compiler.js:16747:15)
    at Object.read_script [as read] (/home/user/work/booking/web/node_modules/svelte/compiler.js:8799:17)
    at tag (/home/user/work/booking/web/node_modules/svelte/compiler.js:15701:34)
    at new Parser$1 (/home/user/work/booking/web/node_modules/svelte/compiler.js:16712:22)
    at Object.parse$I [as parse] (/home/user/work/booking/web/node_modules/svelte/compiler.js:16844:21)
    at collectMessages (/home/user/work/booking/web/node_modules/svelte-i18n/dist/cli.js:186:26)
    at extractMessages (/home/user/work/booking/web/node_modules/svelte-i18n/dist/cli.js:218:5)
    at /home/user/work/booking/web/node_modules/svelte-i18n/dist/cli.js:269:9 {
  code: 'parse-error',
  start: { line: 4, column: 20, character: 78 },
  end: { line: 4, column: 20, character: 78 },
  pos: 78,
  filename: undefined,
  frame: "2:      import { _ } from 'svelte-i18n';\n" +
    '3: \n' +
    '4:      export let name: string;\n' +
    '                       ^\n' +
    '5: \n' +
    '6: </script>'
}

</details>

**Information about your project:**

```
"svelte": "^3.44.0",
"svelte-preprocess": "^4.10.7",
"@sveltejs/adapter-auto": "^1.0.0-next.83",
"@sveltejs/kit": "^1.0.0-next.516",
"vite": "^3.1.0",

```

- Ubuntu 22.04

- `svelte-i18n` version 3.4.1

**Additional context**
Is there some option I'm missing, or is this a bug? Thank you!

**Comment by kaisermann** [comment]
Hey @petrsiegl 👋 

Typescript is not currently supported, I'm afraid. No language that requires preprocessing is supported by the CLI. We could run each file through the preprocessors defined in the user's `svelte.config.js` before parsing them though. Would be the most straight-forward/quickest way of fixing this

**Comment by petrsiegl** [comment]
Thank you very much for quick answer @kaisermann.

That's what I was initially thinking the `--configDir` option would do. It seems to me, it may be not that hard to add support for this. I've never attempted anything like this, but I can try to take a look at this later if you like.

**Comment by kaisermann** [comment]
My bad, [there _is_ code to handle this already](https://github.com/kaisermann/svelte-i18n/blob/main/src/cli/index.ts#L62) and _should_ be working 😅 Will check!

**Comment by kaisermann** [comment]
Ok, this may be happening due to a misuse of the `--config` parameter. Since the svelte config file can now have .mjs and .cjs as extension (AFAIK), I think we should change it to point directly to the config file instead of the directory.

**Comment by petrsiegl** [comment]
Thank you!

Yes, that makes sense to me. From DX perspective, it doesn't hinder anything and it is more flexible anyway.

We need to fix the param name in [CLI docs](https://github.com/kaisermann/svelte-i18n/blob/59691f325c5ba421a3606b741d04443cc171d182/docs/CLI.md?plain=1#L13) as well.

**Comment by kaisermann** [comment]
@petrsiegl can you provide a repro?

**Comment by petrsiegl** [comment]
@kaisermann If I understand correctly, this should work.
In that case I'll create a new minimal Sveltekit project and test it there. I'll try to figure out the problem and let you how it goes.

**Comment by petrsiegl** [comment]
@kaisermann Start repo for sveltekit with i18n:

https://github.com/petrsiegl/svelte-i18n-extract-test

Still doesn't work tried in root dir with:
`./node_modules/svelte-i18n/dist/cli.js extract -c ./svelte.config.js src/lib/Test.svelte`
with error:
```
Error: unexpected token detected in "src/lib/Test.svelte"
A svelte config was detected at "/home/sieglp/workspace/svelte/my-app/svelte.config.js". Make sure the preprocess step is correctly configured."
```

**Comment by kaisermann** [comment]
Can you try again with v3.5.1? I've tested in your repro and it worked as expected 🙏  We were missing a small thing while loading the "svelte.config.js" file

**Comment by petrsiegl** [comment]
Yes, it works perfectly! Thank you so much for your help. Amazing work! :1st_place_medal:
