### ISSUE TITLE
globally expose $_ in svelte?

### ISSUE THREAD

**Issue by chovy** [kaisermann/svelte-i18n#21]
I'd rather not do `import { _ } from 'svelte-i18n` in every file. Is there a way to globally expose this to my app such that all the component files have it?

I'm using rollupjs

**Comment by kaisermann** [comment]
Currently no! As a workaround you can make a quick and naive preprocessor to prepend that statement at the beginning of your svelte components. 

I've been thinking of providing a preprocessor to remove some verbosity (even if it's just a single `import` declaration). I'm not the biggest fan of making things work magically, but this seems to be a nice addition.

**Comment by chovy** [comment]
can you give me an example?

**Comment by shfx** [comment]
This plugin might help: https://github.com/rollup/plugins/tree/master/packages/inject

**Comment by kaisermann** [comment]
@shfx Oh sweet, that's much better than what I suggested. 

Just for the sake of a very crude example of a preprocessor:

```js
const processor = {
	script({ content, attributes, filename }) {
		const hasFormatter = content.match(/import\s*\{.*?(_|format).*?\}\s*from\s*['"]svelte-i18n['"]/);
		if (!hasFormatter) {
			return `import { _ } from 'svelte-i18n';\n` + content;
		}
		return content;
	},
};
```

And you would just pass that to your `preprocess` prop on `rollup-plugin-svelte`.

**Comment by danielquintero** [comment]
Honestly I like the explicitness of `import _ from ...`, I find global imports make it hard to know what's going on (specially if you are learning, like most of us still are with new tech like svelte), I'm sure this is a nice addition but I have mixed feelings should it become the norm (seeing vue-i18n has `$t`) 🤔

**Comment by chovy** [comment]
I think _ is a bad name. It should be $t() because _ is already used by lodash.

**Comment by kaisermann** [comment]
The name is really up to you, you can `import { _ as t } from 'svelte-i18n';` with no issues. However, there's no problem in also exposing it as `t` if it's something that people can understand in a glance what it is (that's the same reason I expose `format` as `_`).

**Comment by chovy** [comment]
Tried this but it didn't work:

```
    inject({
      // use a named export – i.e. insert
      // import { Promise } from 'es6-promise'
	  include: '**/*.js',
	  exclude: 'node_modules/**',
	  _: ['svelte-i18n'],
    }),
```

Navbar.svelte still can't find _

**Comment by kaisermann** [comment]
Oh, rollup will only inject that import AFTER the compilation step. Yeah, a preprocessor is the way 😁

**Comment by kaisermann** [comment]
I'm going to close this as I think it's a bit too magical. If more people show interest in this, we can revive the discussion.
