### ISSUE TITLE
`intl-getcanocicallocales` is probably not a good idea

### ISSUE THREAD

**Issue by brunnerh** [kaisermann/svelte-i18n#228]
Referring to:
- #217

1. The package is huge, relatively speaking.

    ![image](https://github.com/kaisermann/svelte-i18n/assets/834235/e3be6253-28dd-44d8-84be-79e754539a34)
    ([Bundlephobia](https://bundlephobia.com/package/svelte-i18n@3.7.1))

    I was not sure whether that would be representative, e.g. maybe there was some unused code that would not end up in the final bundle, but putting the new `svelte-i18n` version in a test project, that does not look too good.
    > root/_app/immutable/nodes/6.01fdf54a.js/E:/dev/sveltekit-test/node_modules/@formatjs/intl-getcanonicallocales
    > Rendered: 89.91KB (0.54%)
    > Gzip: 23.79KB
    > Brotli: 17.64KB
    > 
    > Rendered is a byte size of individual file after transformations and treeshake.
    > Gzip and Brotli is a byte size of individual file after individual transformations,
    > treeshake and compression.

    (via `rollup-plugin-visualizer`)
2. It breaks usage in the REPL.
    - [3.7.0](https://svelte.dev/repl/d4b051e17f934f3bac4d38ff8f64d298)
    - [3.7.1](https://svelte.dev/repl/8d2b051f1a8041e79839f4ff7b8d8b01)
3. It does not seem to actually solve whatever is the root issue.  
  I [noted in the associated issue](https://github.com/kaisermann/svelte-i18n/issues/209#issuecomment-1672753564) that the issue can happen even with ostensibly valid locales. When testing the new version in my application, interpolation is still broken, but works with v.3.2.0.

**Comment by kaisermann** [comment]
Hey @brunnerh, you're right. I will take a better look at this

**Comment by kaisermann** [comment]
Let's continue on #209
