### ISSUE TITLE
formatjs not working from 2.0.0 onwards

### ISSUE THREAD

**Issue by wootcake** [kaisermann/svelte-i18n#24]
After updating from 1.1.2-beta to 2.0.0 or later, formatted translations are no longer being formatted.

For example:
``{
    "page_indicator": "Page {currentPage} of {totalPages}",
}``

and calling;
``{$_('page_indicator', {
        currentPage: 1,
        totalPages: 10
      })}``

will end up in displaying:
`Page {currentPage} of {totalPages}` instead of replacing the variables.

Downgrading back to 1.1.2-beta fixes makes the formatting functional again.

Has this feature been removed?

**Comment by kaisermann** [comment]
In v2, as stated in the wiki (https://github.com/kaisermann/svelte-i18n/wiki/Formatting#format-or-_-or-t), you should pass your values to be interpolated inside a `values` property, instead of directly to passing them to the options object.

**Comment by wootcake** [comment]
> In v2, as stated in the wiki (https://github.com/kaisermann/svelte-i18n/wiki/Formatting#format-or-_-or-t), you should pass your values to be interpolated inside a `values` property, instead of directly to passing them to the options object.
> 
> `{$_('page_indicator', { values: { currentPage: 1, totalPages: 10 }})}`

Didn't see that change, thanks for the information. However, when adding the `values` property it errors out completely right now:
``TypeError: intl_messageformat__WEBPACK_IMPORTED_MODULE_3__ is not a constructor`` 

I'l see if I can figure out what causes this..

**Comment by kaisermann** [comment]
My bad for not making a v1 to v2 docs in the wiki. Will do soon. You can use the previous version for now, I'll probably deprecate the current v2 until I fix some bugs in the coming week 😬

**Comment by kaisermann** [comment]
Unpublished `v2` and released `1.1.2`. Sorry for the inconvenience!

**Comment by wootcake** [comment]
Formatting still doesn't seem to work in the just released `1.1.2`, but works in the older `1.1.2-beta`

**Comment by kaisermann** [comment]
Ok, now THAT is strange. Both are the same code base. What error are you getting?

**Comment by wootcake** [comment]
No errors at all, just messages not being formatted when using `1.1.2`

**Comment by kaisermann** [comment]
@wootcake I just released `v2.1.0-alpha.2` in case you want to start testing with it. I've also updated the docs and made a quick migration guide from `v1` to `v2`: https://github.com/kaisermann/svelte-i18n/wiki/Migration

**Comment by kaisermann** [comment]
@wootcake I just released `v2.1.0` in case you want to start testing with it. I've also updated the docs and made a quick migration guide from v1 to v2: https://github.com/kaisermann/svelte-i18n/wiki/Migration

Let me know if your issue is fixed after migrating.
