### ISSUE TITLE
Svelte 5.0.2 - Error with this library

### ISSUE THREAD

**Issue by go-aegian** [kaisermann/svelte-i18n#260]
After updating to Svelte 5.0.2 I'm getting this error for this library. Is the library being maintained? Can you upgrade it?

npm error Found: svelte@5.0.2
npm error node_modules/svelte
npm error   dev svelte@"5.0.2" from the root project
npm error Could not resolve dependency:
npm error peer svelte@"^3 || ^4" from svelte-i18n@4.0.0
npm error node_modules/svelte-i18n
npm error   dev svelte-i18n@"4.0.0" from the root project

**Comment by kaisermann** [comment]
Should be solved by version `4.0.1`

**Comment by go-aegian** [comment]
Thank you!
