### ISSUE TITLE
Nested message references / linking messages

### ISSUE THREAD

**Issue by ehsanonline** [kaisermann/svelte-i18n#27]
It would be great if we could use nesting on the json translation files. [Like this](https://www.i18next.com/translation-function/nesting):
```
{
    "nesting1": "1 $_(nesting2)",
    "nesting2": "2 $t(nesting3)",
    "nesting3": "3",
}
```

**Comment by kaisermann** [comment]
I understand the positive side of implementing a way to "link" messages without having to format them separately, but I'd need to think about how it could be done in a way that it keeps the ICU syntax valid. 

The first obstacle here is the underlying `formatjs` lib, which is responsible for parsing those messages. As far as I know, it doesn't support custom generic formats. 

I know that's far from ideal, but as a workaround you can insert the formatter result as a interpolated value:

```json
{
    "nesting1": "1 {nested}",
    "nesting2": "2",
}
```

```svelte
<div>
  {$_('nesting1', { values: { nested: $_('nesting2') }})}
</div>
```

**Comment by ZerdoX-x** [comment]
I thought I could use t10s like this: https://github.com/lokalise/i18n-ally/tree/main/examples/by-features/linked

:(
