### ISSUE TITLE
Sapper usage

### ISSUE THREAD

**Issue by laurentpayot** [kaisermann/svelte-i18n#3]
Simply using the default Sapper webpack template:

```shell
$ npx degit sveltejs/sapper-template my-app
$ cd my-app/
$ npm i
$ npm i svelte-i18n
```

with `src/client.js` including the svelte-i18n example  (only destructured `import { i18n } ` to avoid an import error, want me to open another issue?) like so:

```js
import * as sapper from '../__sapper__/client.js';

import { i18n } from 'svelte-i18n'
import { Store } from 'svelte/store'

/** i18n(svelteStore, { dictionary }) */
let store = new Store()

store = i18n(store, {
  dictionary: {
    'pt-BR': {
      message: 'Mensagem',
      greeting: 'Olá {name}, como vai?',
      greetingIndex: 'Olá {0}, como vai?',
      meter: 'metros | metro | metros',
      book: 'livro | livros',
      messages: {
        alert: 'Alerta',
        error: 'Erro',
      },
    },
    'en-US': {
      message: 'Message',
      greeting: 'Hello {name}, how are you?',
      greetingIndex: 'Hello {0}, how are you?',
      meter: 'meters | meter | meters',
      book: 'book | books',
      messages: {
        alert: 'Alert',
        error: 'Error',
      },
    },
  },
})

/**
 * Extend the initial dictionary.
 * Dictionaries are deeply merged.
 * */
store.i18n.extendDictionary({
  'pt-BR': {
    messages: {
      warn: 'Aviso',
      success: 'Sucesso',
    },
  },
  'en-US': {
    messages: {
      warn: 'Warn',
      success: 'Success',
    },
  },
})

/** Set the initial locale */
store.i18n.setLocale('en-US')


sapper.start({
  target: document.querySelector('#sapper'),
  store
});
```

With 
```
$ npm run dev
```

In my browser I get:
```
client.js:91 Uncaught TypeError: fn is not a function
    at set_store (client.js:91)
    at Module.start (client.js:386)
    at Module../src/client.js (client.js:59)
    at __webpack_require__ (bootstrap:767)
    at bootstrap:903
    at bootstrap:903
set_store @ client.js:91
start @ client.js:386
./src/client.js @ client.js:59
__webpack_require__ @ bootstrap:767
(anonymous) @ bootstrap:903
(anonymous) @ bootstrap:903

```

**Comment by kaisermann** [comment]
I still haven't had the time to play around with sapper yet, so any help with this is welcome :grin:

**Comment by laurentpayot** [comment]
My bad. Sapper client start store property must be a function: 

```js
sapper.start({
  target: document.querySelector('#sapper'),
  store: data => {
    // `data` is whatever was in the server-side store
    store.set(data);
    return store;
  }
});
```
Thanks anyway @kaisermann

**Comment by rveciana** [comment]
Excuse me if it's the wrong place. Did you get the svelte-i18n run in sapper?
I've tried it, but in the first render, the store is not set.
You didn't mention that the store has to be set in the server.js file too.
My example is here: https://github.com/rveciana/sapper-i18n

**Comment by kaisermann** [comment]
@rveciana I haven't messed around with sapper yet, just pure svelte. I will check otu your example!

**Comment by laurentpayot** [comment]
@rveciana yes I could get svelte-i18n run in Sapper for Svelte 2.x.
The problem is that the store returned by the server must be serializable (i.e. without function). So inside the sapper middleware store hook of the server you must delete the `_` function attribute that svelte-i18n adds to the store before sending it. See https://github.com/sveltejs/sapper/issues/230 for more details.

Recently I had some issues (weird dependencies problems) with svelte-i18n but instead of fixing them I'm waiting for [i18n support in Svelte/Sapper 3](https://github.com/sveltejs/sapper/issues/576). :crossed_fingers: 

IMHO if you are starting a new Svelte app, you should use Svelte 3 betas (along with Sapper v0.26.0-alpha.3) and wait for its i18n system to avoid rewriting everything soon… :wink:

**Comment by Mattinn** [comment]
> The problem is that the store returned by the server must be serializable (i.e. without function). So inside the sapper middleware store hook of the server you must delete the `_` function attribute that svelte-i18n adds to the store before sending it. 

Hi @laurentpayot could you provide an example of how that is done? After reading this thread and the one you linked I am quite lost  
```
.use(
    sapper.middleware({
      store: req => {
        return new Store({
          user: req.user,
          get() {
            const res = { ...this._state };
            delete res._;
            return res;
          }
        });
      }
    })

```

**Comment by laurentpayot** [comment]
Hi @Mattinn when I was using Svelte/Sapper (I now use [Elm](https://elm-lang.org/) :heart:) I was doing something like that (simplified and translated from CoffeeScript source, hopefully without errors):

```js
// store.js
import {Store} from 'svelte/store'
import {i18n} from 'svelte-i18n'

let store = new Store({
  locale: 'en'
})

store = i18n(store, {dictionary: {}})
export default store
```
```js
// server.js
import * as sapper from '../__sapper__/server'
import express from 'express'
import {Store} from 'svelte/store'
import defaultStore from '/store'
import {i18n} from 'svelte-i18n'

const app = express()
const defaultValues = defaultStore.get()


// subclassing Store to make its instances serializable
class ServerStore extends Store {
  get() {
    let result = {...super(...arguments)}
    delete result._
    return result
  }
}

const sapperMiddleware = sapper.middleware({
  store: (req, res) => {
    const lang = req.acceptsLanguages(['en', 'fr']) || 'en'
    res.set('Content-Language', lang)
    let store = new ServerStore(defaultValues)
    store = i18n(store, {dictionary: {[`${lang}`]: {foo: "bar"}}})
    store.i18n.setLocale(lang)
    return store
  }
})


app.use(sapperMiddleware)

export default app
```
Hope it helps…

**Comment by Mattinn** [comment]
Thanks @laurentpayot this clears it up quite well !
