### ISSUE TITLE
Programatically change languages

### ISSUE THREAD

**Issue by Antonyacosta78** [kaisermann/svelte-i18n#34]
Is there a way to dinamically change between dictionaries? 

**Describe the solution you'd like**
an exported function from the library that allows to change between dictionaries programmatically

**Describe alternatives you've considered**
I haven't found a workaround yet

**How important is this feature to you?**
Will be a huge improvement to the library, it seems that it's the only thing lacking of the base features of i18n

**Comment by kaisermann** [comment]
Hey 👋

By "changing dictionaries" you mean literally switch all loaded dictionaries with different ones? Or to just switch the current locale and use it's dictionary? 

Can you provide an example of usage of what you want?

**Comment by Antonyacosta78** [comment]
@kaisermann I mean switching locales, sorry for the mistake. I am thinking in a function exported by the package in order to change between locales
Example: 
```
<script>
 import { addMessages, t, changeLocale } from 'svelte-i18n';
 import en from './en.json';
 import es from './es.json';

 addMessages('en', en);
 addMessages('es', es);
 init({ fallbackLocale: 'en' });


</script>

<button on:click={ () => changeLocale('es') } > Click here to change to spanish </button>
```

**Comment by kaisermann** [comment]
Oh, I certainly could do that. But what do you think about just changing the `$locale` store value?

```svelte
<script>
 import { addMessages, t, locale } from 'svelte-i18n';
 import en from './en.json';
 import es from './es.json';

 addMessages('en', en);
 addMessages('es', es);
 init({ fallbackLocale: 'en' });


</script>

<button on:click={ () => $locale = 'es' } > Click here to change to spanish </button>
```

**Comment by Antonyacosta78** [comment]
No, that's just right, thank you! 

Found out that was my mistake for not reading the wiki properly haha. 

Anyways it could be good if the main readme had brief explainations on the features (just personal guess, i am more used to read readme files instead of wikis because those are more common). I don't mind writing some. Are you open to PRs?

**Comment by kaisermann** [comment]
Glad to know it helps 😁 And yeah, of course, PRs are always welcome!
