### ISSUE TITLE
Add similar parameters to the vsprintf function

### ISSUE THREAD

**Issue by tiagodjf** [kaisermann/svelte-i18n#42]
It would be great if we could add variables to translations similarly to [vsprintf](https://github.com/alexei/sprintf.js), example:
```
<script>
addMessages
(
'en',
'validation':
{
'maxChars': 'The "%s" field can contain a maximum of %s characters'
}
);
</script>

<span class="warning"> {$_('validation.maxChars', {}, ['name', 30])} </span>
<!-- The "name" field can contain a maximum of 30 characters -->
```

Thanks!

**Comment by kaisermann** [comment]
Hey @tiagodjf 👋 

That would be outside of the scope of the ICU syntax and I'm not sure if it's worth implementing from our side. However, currently you can achieve something very similar:

```svelte
<script>
addMessages("en", {
  validation: {
    maxChars: 'The "{0}" field can contain a maximum of {1} characters'
  }
});
</script>

<span class="warning"> {$_('validation.maxChars', { values: ['name', 30] })} </span>```

**Comment by tiagodjf** [comment]
Great, it’s basically the same thing, it solves the issue.
Thanks.
