### ISSUE TITLE
Format dates acccording to the current locale

### ISSUE THREAD

**Issue by angryziber** [kaisermann/svelte-i18n#45]
In many localization scenarios, locales can have different formats for dates.
Think `en` vs `jp`, for example. Or `en-US` vs `en-GB`.

It is thus required to define different date formats for each locale, preferably even in the locale json file itself, so a person doing localization would be able to tune the formats if needed.

It's very hard to figure out how to change date formats at all, here is a working example:
```
  i18n.init({
    ...
    formats: {
      date: {
        short: {month: 'numeric', day: 'numeric', year: 'numeric'}, // short seems to be the default
        full: {year: 'numeric', month: 'short', day: 'numeric'}
      }
    }
  })
```

However, it seems to be using exactly the same format for each different locale, maybe according to the browser's default locale?

**Comment by cbxp** [comment]
We actually have realized that dates are formatted according to the initial locale (taken e.g. from path), but when you change locale with `$locale = 'jp'`, it updates all localized texts, but date formats remain according to the previous/initial one. This seems to be a bug

**Comment by kaisermann** [comment]
@cbxp @angryziber There was a bug regarding the memoization of date/time/number formatters which prevented them from being updated when the `$locale` changed, see #47. Can you guys try again in `v2.3.1`?

**Comment by rodoch** [comment]
I'm going to presume this isn't the cause of your issue, but just in case: I believe svelte-i18n, at some level, wraps the Intl API. The Intl API only has access to whatever locales are available in your runtime (server-side: Node.js, client-side: whatever the browser ships with). This bit me recently working with ga-IE localisation in Ireland: Firefox and Edge ship with better localised distros here and svelte-i18n was localising the dates for me, but whenever I opened the app in Chrome the dates were displayed in English as Chrome had no support for the ga-IE locale. In the end the only solution that reliably worked in userland was to use moment.js for date formatting (manually importing ga-IE locale) and svelte-i18n for the rest of the string translation. It works good though, and the way svelte-i18n v3 has broken up the _, number and date functions so they can be tree-shaken reduces extra weight involved with adding an additional library.

Hope I haven't got any of the above wrong @kaisermann

**Comment by kaisermann** [comment]
@rodoch Got pretty much everything right! Thanks for the great explanation 😁

**Comment by rodoch** [comment]
That's a super tip, very clean, thanks. This is a great library, I wouldn't be using Svelte without it. Hoping to do a write up on it somewhere soon!
