### ISSUE TITLE
Getting an object of translation

### ISSUE THREAD

**Issue by RemiKalbe** [kaisermann/svelte-i18n#50]
I have in my JSON something like that:
```json
"countries": {
    "singular": "country",
    "list": {
      "AF": "Afghanistan",
      "AL": "Albania",
      "DZ": "Algeria",
      "AS": "American Samoa",
      "AD": "Andorra",
      "AO": "Angola",
      "AI": "Anguilla",
      "AQ": "Antarctica",
      "AG": "Antigua and Barbuda",
      ...
      }
}
```
and I would like to be able to do that 

```js
$_("countries.list")
```

and get the list of countries as an object.

Right now I get an error telling me that `countries.list` doesn't exist.
For the moment I will probably use the `$dictionary` but it is painful because everything is shallow so I need to manually filter each key to find what I want.

Am I missing something?

**Comment by kaisermann** [comment]
The `_` method will always return a localized `string`. If you want iterate through some items and translate them, you need to have a separate object (like that `list` of yours, loop through it and call the `_` method with the id of each country. The dictionary of messages is not supposed to be something you would iterate over like that 😁.

Here's a simple REPL to demonstrate that: https://svelte.dev/repl/49412f11564b41a183f414177ffc52b9?version=3.18.2

**Comment by RemiKalbe** [comment]
It's not super practical, I literally have the identifier of all the countries to copy and paste 🤡.
Is it possible to get a version of $dictionary not shallow?

**Comment by RemiKalbe** [comment]
If anyone comes into this need, I did this 

```js
import ld from "lodash"

let dic = $dictionary[$locale];
let countries = [];
ld.pickBy(dic, (v, k) => {
  if (k.includes("countries.list")) {
    const key = k.split(".")[2];
    countries.push({ key, value: v });
  }
});
```

It does the trick, but something native could be really cool 😉

**Comment by kaisermann** [comment]
Following what you wanted on the OP, what would`$_("countries.list")` render? It's a POJO, svelte would just output `[object Object]`.

Dictionaries are flatten since #39 and I understand that it's not the optimal solution to have an extra list, but there's currently no other way to do that. Having a deep dictionary only adds complexity to the code and it wasn't necessarily being useful. I still think that using the dictionary to loop through values isn't the right way of doing this, but I'm open to discussion.

(about your workaround: I'd manually import `pickBy` and `includes` so the rest can get tree-shaken.)

**Comment by RemiKalbe** [comment]
I don't want it to be rendered, I just want to get back an object to then use it for a dropdown.
I'll change the import 👍.

**Comment by RemiKalbe** [comment]
Ok, so for some reason my workaround only works server side.
In the browser the $dictionary is undefined.

event tho I have that

```svelte
<script context="module">
  import { waitLocale } from "svelte-i18n";

  export async function preload() {
    return waitLocale();
  }
</script>
```

**Comment by kaisermann** [comment]
Can you provide a repro?

**Comment by RemiKalbe** [comment]
https://svelte.dev/repl/5a7d490941a243e3baec71e7d024e88e?version=3.18.2

**Comment by kaisermann** [comment]
The `async function preload() { ... }` only works in sapper. If you're just using svelte, you can use the `$loading` store: https://github.com/kaisermann/svelte-i18n/blob/master/docs/Locale.md#loading

**Comment by RemiKalbe** [comment]
I'm using Sapper.
Also
```
'loading' is not exported by node_modules/svelte-i18n/dist/runtime.esm.js
```

**Comment by kaisermann** [comment]
Oh okay, so please provide a sapper repro, not a svelte one 😁 A simple .zip helps a lot. 

And my bad, outdated doc. It's called `$isLoading`!

**Comment by RemiKalbe** [comment]
My point was, shouldn't the svelte one works? because it doesn't 😥.
I'll create a zip.

**Comment by kaisermann** [comment]
Move those references to $dictionary and $locale to inside the `$:` block: https://svelte.dev/repl/5589264db1f8400faf5e6465e21071ab?version=3.18.2

**Comment by RemiKalbe** [comment]
Here you are
https://github.com/RemiKalbe/svelte-i18n-repro-sdb

**Comment by kaisermann** [comment]
Hey @RemiKalbe 👋  Sorry for taking so long to answer you. It seems that when you're getting the current dictionary via `let dic = $dictionary[$locale];`, in the client, the `$locale` is, in example, `en-US`. However, since the server doesn't have a navigator object, it sets its `$locale` to `en`. That's the reason for the difference between them both.

**Comment by RemiKalbe** [comment]
What would be great is that if $dictionary[$locale] of a given $locale doesn't exist it fallback to the default one set in the init.

**Comment by RemiKalbe** [comment]
For now, I'll just to that, thank you for solving my issue 😉

```js
let dic =
      typeof $dictionary[$locale] === "undefined"
        ? $dictionary["en"]
        : $dictionary[$locale];
```
