### ISSUE TITLE
A way to get the current local

### ISSUE THREAD

**Issue by Bigaston** [kaisermann/svelte-i18n#54]
For a project, I need to get the current locale selected by the plugin (chosen between the browser local or the fallback locale), to send it to my server. There is a way to do that?

I've thinked about a `getCurrentLocale()` methode that send maybe the code of the locale, or `getCurrentLocaleJson()` that return the name of the JSON File.

This feature is not very important, if there is no way to do that, I can find a way to do it, but if there is a method juste for that it's can be cool!

Thanks for this very usefull lib!

**Comment by kaisermann** [comment]
Hey @Bigaston 👋 

If you're inside a svelte file you can import the `locale` store and just use it in your code: `$locale`

If you're not, you can import the `locale` store and use the `svelte/store`'s `get` method to get its value:

```js
import { get } from 'svelte/store'
import { locale } from 'svelte-i18n'

const currentLocale = get(locale)
```

I'll think about a morestreamlined version, if more people need this outside of a svelte context.

**Comment by Bigaston** [comment]
Okay!
Thanks for yout quick awnser! I'm going to do that ^^
