### ISSUE TITLE
Right to left (example)

### ISSUE THREAD

**Issue by dhrp** [kaisermann/svelte-i18n#60]
**Is your feature request related to a problem? Please describe.**
Thanks for the excellent work (and example). Because I'm working on a site that includes Arabic (right-to-left) I figured out how I'd support that using svelte-i18n. 

**Describe the solution you'd like**
I updated the example to include RTL Arabic. The source can be found here: https://github.com/dhrp/svelte-i18n/tree/master/example

**Describe alternatives you've considered**
One thing I considered, is adding 'rtl' more deeply, but for now I've just the directionality css class as a internationalization string instead of first making it a variable.

```html
<nav class={$_('direction')}>
``` 
Using a different script influences in which language you write the other languages.. I'd suggest writing them in the native language.

**How important is this feature to you?**
I think it's important to support RTL, but it appears support is a matter of updating the example, not core.

**Additional context**
I can easily make this a PR.

<img width="981" alt="Screenshot 2020-03-28 18 51 39" src="https://user-images.githubusercontent.com/2017300/77829886-2f543d80-7125-11ea-86ad-5e0cd3d7b773.png">

**Comment by kaisermann** [comment]
Hey @dhrp! That addition to the example would be great! Feel free to make the PR if you have the time 😁 . What kind of difficulties are you encountering while supporting RTL languages?
