### ISSUE TITLE
Svelte Example?

### ISSUE THREAD

**Issue by kieranhall** [kaisermann/svelte-i18n#63]
I see the example app is implemented with Sapper.  Are there any up-to-date examples for using this library with Svelte.  e.g. How about showing an example integrating with  https://github.com/sveltejs/template ?

Asking as when I tried to integrate with an existing Svelte app, I had no success.

**Comment by nfk** [comment]
I have just found a great post about how to use svelte-i18n https://medium.com/i18n-and-l10n-resources-for-developers/how-to-localize-a-svelte-app-with-svelte-i18n-9e86cc9eb727. Maybe it can help.

**Comment by kieranhall** [comment]
I had indeed seen this article and the accompanying repo, however, this guide uses  svelte-i18n ^1.1.2-beta... Which is quite outdated, even considering these docs: https://github.com/kaisermann/svelte-i18n/blob/master/docs/Migration.md#from-v1-to-v2.  Did you have success using the linked post and svelte-i18n version ~3.0.0?

**Comment by nfk** [comment]
The previous link helps me a lot for understanding how to use i18n on JS project. In fact to use the last version of svelte-i18n the [doc](https://github.com/kaisermann/svelte-i18n/tree/master/docs) provided in that repo solves all of my issues. You can refer to this [commit](https://gitlab.com/nicofonk/nextrun/-/commit/266c2b016cabf717f76d0f91dd44ec58ddfcf494) of my personal project to see how to use svele-i18n v3 on a Svelte app.

**Comment by kieranhall** [comment]
Your commit looks really helpful!  I will look over that when I come back to the i18n topic (currently on hold)... Thanks for the help!
