### ISSUE TITLE
get locale from HTTP request header

### ISSUE THREAD

**Issue by 5amch3n** [kaisermann/svelte-i18n#67]
It doesn't seem to work well with SSR - Everybody gets the same server-rendered result using the default locale, no matter what locale they're using.

So, is it possible to extract locale from HTTP request header on the server side and render the HTML result based on the user's locale?

**Comment by kaisermann** [comment]
@5amch3n Hey 👋 This was in the scope of the library when I first developed it, but it's something that makes complete sense. However, I have little experience with SSR and don't have a lot of time right now to focus on that. Whenever possible, I'll definitely give it a try!

**Comment by jayk-e** [comment]
@5amch3n i'm using it like this with ssr & lang cookie in sapper

```js
// server.js
import { registerLanguages, initLanguages, DEFAULT_LANG } from './utils/i18n.utils';
registerLanguages();

...

app.use(
  (req, res, next) => {
    const lang = req.acceptsLanguages()[0] || DEFAULT_LANG;
    res.lang = req.cookies.lang || lang.split('-')[0];
    initLanguages(res.lang);
    next();
  },
);
```

```js
// i18n.utils.js
import {
  register, locale, init, getLocaleFromNavigator,
} from 'svelte-i18n';
import Cookies from 'js-cookie';
// import { APP_DOMAIN } from './constants';

export const DEFAULT_LANG = 'en';

export const registerLanguages = () => {
  register('en', () => import('../lang/en.locale'));
  register('cs', () => import('../lang/cs.locale'));
};

export const initLanguages = (lang = Cookies.get('lang')) => init({
  fallbackLocale: DEFAULT_LANG,
  initialLocale: lang || getLocaleFromNavigator(),
});

export const setLang = (lang) => {
  locale.set(lang);
  Cookies.set('lang', lang, {
    expires: 365 * 5,
    secure: process.env.NODE_ENV !== 'development',
    // domain: APP_DOMAIN,
    sameSite: 'strict',
  });
};
```

```js
// _layout.svelte
import { waitLocale } from 'svelte-i18n';

export async function preload(page, { lang }) {
  return waitLocale(lang);
}
```

**Comment by 5amch3n** [comment]
@jayk-e Cool! And last week I worked it out too (using similliar ideas to yours).

```javascript
// server.js
// ...
(req, res, next) => {
  let locale = 'en'
  if(req.headers.cookie) {
    locale = (req.headers.cookie.split(';').find(kvp => kvp.trim().startsWith('locale='))||'').split('=')[1];
  }
  req.session = { locale: locale||'en' }
}
// ...
sapper.middleware({
  session: (req, res) => req.session||{}
})
```

```javascript
// _layout.svelte
<script context="module">
  import { addMessages, init } from 'svelte-i18n'
    export async function preload(page, session) {
      let locale = (session||{}).locale||'en';
      const res = await this.fetch(`/api/i18n/messages?path=${page.path}&locale=${locale}&window=${typeof window}`)
      const messages = await res.json()
      addMessages('en', messages)
      return { messages }
  }
</script>

<script>
  export let messages;
  import { stores } from '@sapper/app';
  const { page, session } = stores();
  $: {
    // the `locale` param is always 'en', but the actual locale is not.
    // It doesn't matter, as what matters is updating the dict.
    init({
      fallbackLocale: 'en',
      initialLocale: 'en'
    })
    addMessages('en', messages)
    if(typeof window !== 'undefined' && $page.path !== '/') {
      // fetch module-specific messages from within the browser
      fetch(`/api/i18n/messages?path=${$page.path}&locale=${$session.locale}`)
        .then(res => res.json())
        .then(data => {
          Object.assign(messages, data)
          addMessages('en', messages)
        })
    }
  }
</script>
```

We don't fetch messages from the sapper server itself, we fetch them from the API server instead.

**Comment by kaisermann** [comment]
Thanks for both your inputs! I've been trying to create a sapper template with i18n working out of the box (https://github.com/kaisermann/sapper-template-i18n) and your code helped a lot 😁

I'm not satisfied with `init`ing/setting the locale for every request. A suggestion here, from someone who has more server-side experience, would be great.

**Comment by jayk09** [comment]
@kaisermann i'm detecting request for the main source only, but it throws me an error when i init the i18n.. i'll try again in time and let you know if i was able to solve it..
this actually doesn't work:
```js
const docRegex = new RegExp(/^([^.?#@]+)?([?#](.+)?)?$/);

// page load detection
app.use(
  (req, res, next) => {
    res.isDocument = docRegex.test(req.originalUrl);
    next();
  },
);

// init language
app.use(
  (req, res, next) => {
    if (res.isDocument) {
      const lang = req.acceptsLanguages()[0] || DEFAULT_LANG;
      res.lang = req.cookies.lang || lang.split('-')[0];
      initLanguages(res.lang);
      next();
    }
  },
);
```

**Comment by kaisermann** [comment]
@jayk09 Managed to adapt your code add added it to the https://github.com/kaisermann/sapper-template-i18n template.

**Comment by jayk09** [comment]
@kaisermann cool, but you’re sill running the `init` fnc with every request (js, css, images etc.), right?.. I was about doing it only once on the server..

**Comment by kaisermann** [comment]
@jayk09 The init itself only happens once! You can see [here](https://github.com/kaisermann/sapper-template-i18n/blob/master/src/i18n.js#L48) that it's only called once and the return of that `i18nMiddleware` is the actual middleware.

**Comment by jayk09** [comment]
@kaisermann try to log `req.originalUrl` in your middleware. You should see all requested resources in your terminal (it’s on server so not in browser console). It runs for every resource incl. images, styles etc..
