### ISSUE TITLE
CLI seems like it wasn't installed

### ISSUE THREAD

**Issue by perpetualgrimace** [kaisermann/svelte-i18n#70]
When attempting to use the CLI, I get `-bash: svelte-i18n: command not found`. Sorry — I feel like I'm missing something really basic here. 😅

**Information about your project:**

- Your operating system: MacOS 10.14.6

- `svelte-i18n` version: 3.0.3

- Whether your project uses Webpack or Rollup: Rollup

**Comment by kaisermann** [comment]
Hey @perpetualgrimace 👋  Did you installed it globally or only locally? If only locally, does your bash consider your `node_modules` binaries?

**Comment by perpetualgrimace** [comment]
I had only installed it locally. Now that I think about it, needing to instal a CLI globally makes a lot of sense. 😅

That seems to have done the trick — I would just suggest being a bit more explicit in the docs!
