### ISSUE TITLE
Formatting not working in sapper component

### ISSUE THREAD

**Issue by huevoncito** [kaisermann/svelte-i18n#71]
**Describe the bug**

```
import { waitLocale, _, isLoading, locale } from 'svelte-i18n';

<!-- Works as expected, changes reactively -->
<span>{$locale}</span>

<!-- Prints the correct string for initial locale but does not change when locale changes  -->
<span>{$_("some_dict_key" ) }</span>

<!-- For good measure, I tried this too. Still no reactivity -->
<span>{$_("some_dict_key" , $locale) }</span>
```

**Logs**
No error logs

**To Reproduce**
Other factors that might be relevant

1. Using rollup and I get [this error](https://github.com/kaisermann/svelte-i18n/blob/50154dc59a11317b2646e7e3fcc3688c58f58911/docs/FAQ.md). I know it is supposed to be innocuous but I wonder if it holds the clue

2. JSON import has been added to rollup config and is clearly working because the initial render is correct.

3. `register` and `init` are being called in `src/client.js`

4. All this is happening in `routes/_layout.svelte` Just in case it helps, here is the full code of that file.

```
<!-- Wait for the locale to be set properly on the server -->
<script context="module">
	import { waitLocale, format, isLoading, locale } from 'svelte-i18n';
        export async function preload() {
	   return waitLocale();
       }
</script>

<script >

	// import global nav and footer
	import Nav from '../components/Nav.svelte';
	import Footer from '../components/Footer.svelte';

	//Reactive var passed to nav. Changes on scroll.
	export let isFixedTop = false;
</script>

<!-- import global sass -->
<style lang='scss' global>
 @import "../assets/styles/main.scss";
</style>


<!-- If locales are loaded, render the UI -->
<Nav { isFixedTop }/>
<div style='background: white !important'>{ $format( "some_dict_key" ) }</div>
  <main>
    <slot></slot>
   </main>
<Footer />

```

5. I have tried with `_`, `t`, and `format` - same result each time. It exports as a store 

6. I have tried with and without `isLoading`. Makes no difference

**Expected behavior**
Expect the value to update as locale updates

## UPDATE 1
I just logged `$dictionary.en['some_dict_key]` and `$dictionary.fr['some_dict_key']` in the template (by dumping them into a `<div>`). When `en` is the initial locale, `$dictionary.fr['some_dict_key']` is undefined. However, when `fr` is the initial locale, both values are defined and the reactivity works as intended when locale is toggled through the UI.

## UPDATE 2
After re-reading the docs (again), it see that async message loading only loads current locale. I think this is the problem. When I change to `addMessages` it works as intended. 

**Stacktraces**
No errors thrown

**Information about your project:**
- Brave 1.886

- `svelte-i18n` version 3.0.3 (latest)

- Using rollup

That's all I got. Thanks for making this package. I hope I'm missing something stupid!!

**Comment by kaisermann** [comment]
Hey @huevoncito 👋  Can you test with version `v3.0.4`? I've just fixed a bug related to asynchronously loading messages. If your issue still persists, would you be able to share a repro? Just tested your `_layout.svelte` file and everything seems to be working here.

**Comment by huevoncito** [comment]
@kaisermann thanks for the quick reply. Have updated to 3.0.4 and still have the same issue.

In case it helps, here's `i18n.js`

```
import { register, init, getLocaleFromNavigator, getLocaleFromHostname } from 'svelte-i18n'

register('en', () => import('../lang/en.json'))
register('fr', () => import('../lang/fr.json'))

init({
  fallbackLocale: 'en',
  initialLocale: 'en'
})

```

It is imported into `src/server.js` and `src/client.js`.

**Comment by jbg** [comment]
I had an issue where 100% of the time in Chrome, and about 20% of the time in Firefox, any use of the locale machinery in `_layout.svelte` would fail to react to the locale being changed. The fix for me was to change:

```
init({fallbackLocale, initialLocale});
start({target});
```

to:

```
init({fallbackLocale, initialLocale})
  .then(() => start({target}));
```

It seems like `waitLocale()` in preload should have been sufficient, but apparently not.

**Comment by kaisermann** [comment]
Hey, @huevoncito 👋 Sorry for taking so long to come back here. This is expected behavior in the sense that we only load your current and fallback locales. If you have `en` as your fallback locale, it's always loaded, even if the current locale is `fr`. This was decided because there's no way to know if we're going to need the fallback locale or not and the format call must be synchronous.
