### ISSUE TITLE
Sapper template: lang attribute of hmtl tag in template.html

### ISSUE THREAD

**Issue by tidiview** [kaisermann/svelte-i18n#73]
Hi.
How do you plan to deal with the attribute `lang=en` in the `html` tag of `template.html`?
It needs to be reflecting a locale, doesn't it?
(made also another issue in the sapper template repo)

**Comment by ssergdev** [comment]
What about language definition in _layout.svelte? `<main lang={$locale}>` I think, the nested language definition is semantically valid. Isn't it?

**Comment by tidiview** [comment]
yes ok,
may be,
_but_
the question is:
should the app be `html lang='en'` ??!!??

**Comment by tidiview** [comment]
in code you can do document.documentElement.setAttribute('lang', 'whatever')
you can make that reactive as well: $: document.documentElement.setAttribute('lang', lang)

**Comment by kaisermann** [comment]
Quick reminder that `svelte-i18n` already modifies the `lang` attribute whenever the `$locale` vale changes: https://github.com/kaisermann/svelte-i18n/blob/master/src/runtime/stores/locale.ts#L56

The only issue right now is how to reflect that during SSR

**Comment by tidiview** [comment]
that is my question.

**Comment by Vakil-Parth** [comment]
Does any one have solution for this? I need to set lang attribute in ssr.
