### ISSUE TITLE
Format message from external js file

### ISSUE THREAD

**Issue by tonprince** [kaisermann/svelte-i18n#75]
How can I format a message in an external js file?

I am using Framework7 Svelte and have some message to localize in the routes.js component.

I am trying to format the message:

```
import { format } from 'svelte-i18n';
import { get } from "svelte/store"

get(format("routes.leavePage"))
```

Is there any low level API I can call to get the localized message?

**Comment by kaisermann** [comment]
Unfortunately, the low level `formatMessage`  method is not exported, but you could subscribe to the `format` store instead of using the `get` method.

```js
import { format as $format } from 'svelte-i18n'

let format
$format.subscribe(f => format = f)

format('routes.leavePage')
```

And you'd be able to use the `format` method in your js file while also having it automatically update according to the current locale.

**Comment by tonprince** [comment]
Thanks, that works :-)
