### ISSUE TITLE
Variable in my text

### ISSUE THREAD

**Issue by mjablecnik** [kaisermann/svelte-i18n#76]
When I have in my JSON text some variable: 
```
"info_text": "Už umíte úspěšně napsat celkem 6 nových slov.",

"info_text": "Už umíte úspěšně napsat celkem {0} nových slov.",
```
How can I write value of my variable into the text?

**Comment by kaisermann** [comment]
Hey @mjablecnik 👋  you can check how to use the ICU syntax [here](https://formatjs.io/docs/icu-syntax)! For your example, you could do:

`"info_text": "Už umíte úspěšně napsat celkem {num} nových slov.",`

and in your component:

`{$_('info_text', { values: { num: 6 }})}
`
