### ISSUE TITLE
Unexpected token (Note that you need @rollup/plugin-json to import JSON files)

### ISSUE THREAD

**Issue by agustinl** [kaisermann/svelte-i18n#81]
**Is your feature request related to a problem? Please describe.**
Unexpected token (Note that you need @rollup/plugin-json to import JSON files) #28 

**Describe the solution you'd like**
- Add [@rollup/plugin-json](https://github.com/rollup/plugins/tree/master/packages/json) like dependency.
- And `rollup.config.js` example:

```javascript
// rollup.config-js

import json from '@rollup/plugin-json';

export default {
    client: {
        // ... other configs
        plugins: [
            // other plugins
            json(),
            // another stuffs
        ],
        // ... other configs
    },

    server: {
        // ... other configs
        plugins: [
            // other plugins
            json()
        ],
        // ... other configs
    },
};
```

**How important is this feature to you?**
Prevent error
```
✗ server
Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
1: {
2:   "title": {
            ^
3:     "index": "Sapper project template!"
4:   },
```

**Comment by gavinr** [comment]
I'm getting the same issue here. I ran:

```
npm install @rollup/plugin-json --save-dev
```

... but then I get a _different_ error, same as here: #48

**Comment by agustinl** [comment]
Hi @gavinr are you using sapper? [Here ](https://github.com/agustinl/website/blob/master/rollup.config.js) is my rollup.config.js file, maybe help you

**Comment by gavinr** [comment]
@agustinl thanks, but no I'm using svelte only (no sapper)

**Comment by kaisermann** [comment]
This is not an issue with `svelte-i18n`, but I've added a small section in the getting started document to help some folks out. Thanks for the patience 😁
