### ISSUE TITLE
Using svelte-i18n with named slots

### ISSUE THREAD

**Issue by vcheeze** [kaisermann/svelte-i18n#86]
I have a simple Dialog.svelte components that takes named slots, i.e.
```html
<slot name="header" />
<slot name="body" />
```

I try to use `svelte-i18n` when passing content to these slots, like this
```html
<h3 slot="header">{$_('dialog.title')}</h3>
<p slot="body">{$_('dialog.body')}</p>
```

However, the i18n keys are not found by `svelte-i18n`, and the above snippet is being rendered as
```html
<h3 slot="header">dialog.title</h3>
<p slot="body">dialog.body</p>
```

I'm not sure if I am missing something in my configuration for `svelte-i18n`. When I use it on HTML elements besides slots, it seems to work correctly.

**Info that might help**:
- OS: Linux Mint 19.3 (Cinnamon 4.4.8)
- `svelte-i18n` version: 3.0.4
- Bundler: Rollup

**Comment by vikaspuri-goswami** [comment]
I am also facing same issue and i18n keys are not found.

**Comment by kaisermann** [comment]
Hey @vcheeze and @vikaspuri-goswami 👋  

Would you be able to share a repro project?

**Comment by vikaspuri-goswami** [comment]
@kaisermann : I am unable to share a repo project, but I have followed all steps mentioned in this article. https://medium.com/i18n-and-l10n-resources-for-developers/how-to-localize-a-svelte-app-with-svelte-i18n-9e86cc9eb727

Please let me know, if anything wrong in this article.

I am using svelte: "3.0.0" and svelte-i18n: "3.0.4" version.

**Comment by willnix86** [comment]
+1

**Comment by kaisermann** [comment]
I wasn't able to reproduce the issue with named slots. Something like

![image](https://user-images.githubusercontent.com/12702016/107974453-63cb2500-6f95-11eb-919a-a9664c90e3f2.png)

Seems to work quite well
