### ISSUE TITLE
Warning about 'this' keyword usage

### ISSUE THREAD

**Issue by riccardolardi** [kaisermann/svelte-i18n#88]
I'm working on a sapper project. I get this `The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten` after importing `{ waitLocale }` from `svelte-i18n`. I've found it's related to rollup. Any hint on this?

**Comment by kaisermann** [comment]
Hey @riccardolardi 👋 

You can check the answer for that here: https://github.com/kaisermann/svelte-i18n/blob/master/docs/FAQ.md

**Comment by bartosjiri** [comment]
The provided answer resulted in issue [https://github.com/sveltejs/sapper/issues/1380](https://github.com/sveltejs/sapper/issues/1380) for me.
