### ISSUE TITLE
svelteI18n is not defined 

### ISSUE THREAD

**Issue by fgruchala** [kaisermann/svelte-i18n#9]
Hi,

Thanks for your work :)

I created a directory called "i18n" (original) in which, I have an index.js and a fr-FR.js

**index.js**
```javascript
import {dictionary, locale} from 'svelte-i18n';
import frFr from './fr-FR';

dictionary.set({
  'fr-FR': frFr
});
```

**fr-FR.js**
```javascript
export default {
  APP: {
    NAME: 'Camembert',
  },
};
```

When I want to use it, I have this message in the console 
`svelteI18n is not defined at main.js`

Here is my **main.js**

```javascript
import App from './App.svelte';
import './i18n';

const app = new App({
  target: document.body,
});

export default app;
```

My IDE (Webstorm) and the compiler say that svelte-i18n is a unresolved module ... but I installed it via npm and it's in my package.json
`"svelte-i18n": "^1.0.4"`

Can you help me with that ?

**Comment by kaisermann** [comment]
Hi! My bad! It seems the `.mjs` file was not being included on the package bundle for some reason... 

Fixed on `v1.0.7` 🙏
