### ISSUE TITLE
Export Options interface

### ISSUE THREAD

**Issue by albertms10** [kaisermann/svelte-i18n#90]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to add type definitions to the `INIT_OPTIONS` object in a custom `i18n.ts` config file. The `ConfigureOptions` exported interface located in [`runtime/types/index.ts`](https://github.com/kaisermann/svelte-i18n/blob/f1ba910110cae23110bb21192f4b86fd43a7bd2c/src/runtime/types/index.ts) has an incomplete definition of the object properties, and the complete interface is located in [`runtime/configs.ts`](https://github.com/kaisermann/svelte-i18n/blob/f1ba910110cae23110bb21192f4b86fd43a7bd2c/src/runtime/configs.ts) (`Options`), but is not exported.

**Describe the solution you'd like**
In order to add proper type definitions to external TypeScript files, the `Options` interface should be exported or both interfaces may be merged at some point.

**Describe alternatives you've considered**
Just ignore TypeScript typing, but it’s not the desired approach.

**How important is this feature to you?**
Not in a high priority, but I think it requires a small amount of work to improve this situation.

**Additional context**
https://github.com/kaisermann/svelte-i18n/blob/f1ba910110cae23110bb21192f4b86fd43a7bd2c/src/runtime/types/index.ts#L50-L55
https://github.com/kaisermann/svelte-i18n/blob/f1ba910110cae23110bb21192f4b86fd43a7bd2c/src/runtime/configs.ts#L10-L16

**Comment by kaisermann** [comment]
Hey, @albertms10! Done in `v3.1.0` 🎉  As you suggested, I merged both types!
